#!/usr/bin/env bash
# A Bash script that displays To infinity and beyond indefinitely
# with a 2-second sleep in between each iteration

while true
do
    echo "To infinity and beyond"
    sleep 2
done
