#!/usr/bin/env bash
# A Bash script that stops all 4-to_infinity_and_beyond processes
# shellcheck disable=SC2009

ps aux | grep "4-to_infinity_and_beyond" | grep -v "grep" | awk '{print $2}' | xargs kill
