#!/usr/bin/env bash
# This script lists the content of the current directory, 
# displaying only the part of the name after the first dash (-)
for file in *
do
    echo "$file" | cut -d '-' -f2-
done
